### ISSUE TITLE
docker and upload file volume

### ISSUE THREAD

**Issue by krokrodyle** [solidnerd/docker-bookstack#151]
Hello,

I am experiencing a minor problem with the use of bookstack.
When I upload an image, it works well but as soon as I restart the container it no longer appears.

We immediately think of a problem of volume. I load my docker image like this:

`docker run --net bookstack_nw --name bookstack
-e DB_HOST = bookstack_db: 3306
-e DB_DATABASE = bookstack
-e DB_USERNAME = garfi
-e DB_PASSWORD = MYPASS 
-v uploads:/volume1/docker/bookstack/upload
-v storage-uploads:/volume1/docker/bookstack/storage-uploads
-p 8090:80
solidnerd/bookstack: 0.26.2`

And actually there is nothing in my directory / volume1 / docker / bookstack.
I proceed in the wrong way?
If you could tell me the right way to go, I'm not yet totally comfortable with docker.

thank you so much

**Comment by polarathene** [comment]
`/volume1/docker/bookstack/` is the local / host system? Volume mounts are `host:docker` order. So you would want:

```
/volume1/docker/bookstack/upload:/var/www/bookstack/public/uploads
/volume1/docker/bookstack/storage-uploads:/var/www/bookstack/storage/uploads
```

What your syntax was doing, was creating docker volume container and assigning it to that path inside the docker container, but you want to use the ones I've shown above. Providing a filepath instead on the left(host) side, which I assume you wanted, is a volume bind mount, meaning it references that location on your filesystem instead of using docker to manage the data.

**Comment by krokrodyle** [comment]
thx for reply, I found the solution on the wiki for my case:
https://wiki.chairat.me/books/docker/page/how-to-deploy-bookstack-wiki-app
-v bookstack-uploads:/var/www/bookstack/public/uploads
-v bookstack-storage:/var/www/bookstack/public/storage
