### ISSUE TITLE
SAML2 support missing

### ISSUE THREAD

**Issue by joshuakraitberg** [SolidNerd/docker-bookstack#388]
SAML2 is an alternative authorization flow often used in the same places LDAP is.

The documentation for how SAML2 is enabled can be found here:
https://www.bookstackapp.com/docs/admin/saml2-auth/

As part of this change, several required and optional values are to be added to  the .env file.  
The ideal place to do this is in docker-entrypoints.sh using existing template pattern.  

Some of these values must default to false as specified in the
documentation, some must default as null.

An example of usage can be found here:
https://goauthentik.io/integrations/services/bookstack/

**Comment by ssddanbrown** [comment]
It's been a while since I tested, but AFAIK, you should be able to just define your required options as environment variables on the container, and they'd carry across to BookStack. They don't have to be part of the original `.env` set-up by the script and, unless required for some reason, I'd advise they're not added otherwise it widens the scope of what this container setup needs to support whilst also requiring this project to track any possible changes to config defaults in BookStack itself.
