### ISSUE TITLE
Code editor offscreen 

### ISSUE THREAD

**Issue by awkwardconcepts** [solidnerd/docker-bookstack#42]
I upgraded from 0.16.2 to 0.17.0 by updating the tag of the image in the docker-compose file. 

When I edit pages that I had previously created with code blocks, they are split into a code block for each line and display off of the page.

Any assistance would be appreciated.

**Comment by ssddanbrown** [comment]
Hi @awkwardconcepts,
I'd advise moving this issue over to the [BookStackApp/BookStack](https://github.com/BookStackApp/BookStack) project instead since it's not an issue with this docker project but much more likely an issue with BookStack itself.

PS. Try a hard refresh when in the editor (Usually Ctrl+F5) and see if that fixes things.
