### ISSUE TITLE
Bookstack container starts, then stops

### ISSUE THREAD

**Issue by triDcontrols** [solidnerd/docker-bookstack#93]
used the docker compose method, and container starts, then stops. the logs for the container are below. 

`wait-for-db: waiting for mysql:3306,
wait-for-db: waiting for mysql:3306,
wait-for-db: done,
Do not run Composer as root/super user! See https://getcomposer.org/root for details,
> php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');",
> php -r "!file_exists('bootstrap/cache/compiled.php') || @unlink('bootstrap/cache/compiled.php');",
Loading composer repositories with package information,
Installing dependencies (including require-dev) from lock file,
Nothing to install or update,
Generating optimized autoload files,
> Illuminate\Foundation\ComposerScripts::postAutoloadDump,
> @php artisan package:discover,
Discovered Package: barryvdh/laravel-debugbar,
Discovered Package: barryvdh/laravel-dompdf,
Discovered Package: barryvdh/laravel-ide-helper,
Discovered Package: barryvdh/laravel-snappy,
Discovered Package: fideloper/proxy,
Discovered Package: intervention/image,
Discovered Package: laravel/socialite,
Discovered Package: socialiteproviders/manager,
Package manifest generated successfully.,
> php artisan cache:clear,
Cache cleared successfully.,
> php artisan view:clear,
Compiled views cleared!,
**************************************,
*     Application In Production!     *,
**************************************,
,
Command Cancelled!,
Migration table created successfully.,
wait-for-db: waiting for mysql:3306,
wait-for-db: done,
Do not run Composer as root/super user! See https://getcomposer.org/root for details,
> php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');",
> php -r "!file_exists('bootstrap/cache/compiled.php') || @unlink('bootstrap/cache/compiled.php');",
Loading composer repositories with package information,
Installing dependencies (including require-dev) from lock file,
Nothing to install or update,
Generating optimized autoload files,
> Illuminate\Foundation\ComposerScripts::postAutoloadDump,
> @php artisan package:discover,
Discovered Package: barryvdh/laravel-debugbar,
Discovered Package: barryvdh/laravel-dompdf,
Discovered Package: barryvdh/laravel-ide-helper,
Discovered Package: barryvdh/laravel-snappy,
Discovered Package: fideloper/proxy,
Discovered Package: intervention/image,
Discovered Package: laravel/socialite,
Discovered Package: socialiteproviders/manager,
Package manifest generated successfully.,
> php artisan cache:clear,
Cache cleared successfully.,
> php artisan view:clear,
Compiled views cleared!,
**************************************,
*     Application In Production!     *,
**************************************,
,
Command Cancelled!,
[2018-07-23 00:57:38] production.ERROR: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cache' already exists (SQL: create table `cache` (`key` varchar(191) not null, `value` text not null, `expiration` int not null) default character set utf8mb4 collate utf8mb4_unicode_ci) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cache' already exists (SQL: create table `cache` (`key` varchar(191) not null, `value` text not null, `expiration` int not null) default character set utf8mb4 collate utf8mb4_unicode_ci) at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cache' already exists at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458)"} [],
,
                                                                               ,
  [Illuminate\Database\QueryException]                                         ,
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cache' alre  ,
  ady exists (SQL: create table `cache` (`key` varchar(191) not null, `value`  ,
   text not null, `expiration` int not null) default character set utf8mb4 co  ,
  llate utf8mb4_unicode_ci)                                                    ,
                                                                               ,
,
                                                                               ,
  [PDOException]                                                               ,
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cache' alre  ,
  ady exists                                                                   ,
                                                                               ,
,`

**Comment by windhamwong** [comment]
Why are you waiting for a simple solution for days without doing your own research?
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cache' already exists ,
this is SQL error, may need switching the initial script to start the docker. Please do not use docker if you can't understand the mechanism.

**Comment by BradLugo** [comment]
This seems to be an issue with BookStack's migration scripts and it appears there's a similar issue open in their repo already: https://github.com/BookStackApp/BookStack/issues/1700

Edit: I just realized this issue is much older than the version that was causing this error for me. Apologizes if it's not completely relevant but perhaps it'll help anyone who comes across this issue

**Comment by nmehlei** [comment]
I can confirm that this is still an issue. I tried around 10-12 deployments with the newest version (0.27.5) of which only one or two seemed to succeed, all other ones failed because of this "Table already exists" error. I'm not sure why those two succeeded but I assume it is some sort of race condition. 

Following the suggestion from the link posted by @BradLugo I could successfully deploy Bookstack in an AKS environment with version 0.26.3, the latest version before 0.27.x.

**Comment by nmehlei** [comment]
I was wrong in my previous comment, it does not relate to the version number, it seems to be related to the database migrations. Directly after running the container, bookstack is executing all necessary database migrations and only becomes accessible afterwards. As this can take a moment, kubernetes assumes (via liveness probe and readiness probe) that the container does not work correctly and re-creates it, thus interrupting the database migrations and leaving the database in an inconsistent state from which the next container neither can work nor resume the database migrations. In a kubernetes environment (like AKS), this can be fixed by increasing the time until liveness probes and readiness probes take effect.

This should be fixed with the following PR
https://github.com/helm/charts/pull/21243

In the case of this issue, docker-compose should also allow a similar change which might fix this problem.

**Comment by Sam36502** [comment]
I'm having what seems to be a similar issue.
The app container stops because artisan was expecting some user input here:

```
app_1      | > @php artisan view:clear
app_1      | Compiled views cleared!
app_1      | wait-for-it: waiting 45 seconds for db:3306
app_1      | wait-for-it: db:3306 is available after 0 seconds
app_1      | **************************************
app_1      | *     Application In Production!     *
app_1      | **************************************
app_1      |
app_1      |  Do you really wish to run this command? (yes/no) [no]:
app_1      |  > Command Canceled!
```
